### ISSUE TITLE
Issue on iOS Safari Landscape (iPhone 8, iOS 11)

### ISSUE THREAD

**Issue by andreivictor** [mvasin/react-div-100vh#14] opened 2019-01-10 07:44 UTC
I've found the following issue on iOS Safari, landscape mode:

I've deleted the bottom element containing the text "Something else goes here after the full window height div....", but a scrollbar is still present in browser.

Screenshots attached:
https://imgur.com/a/fFXrHft

.... or live demo on: https://andreivictor.ro/div100/.

**Comment by bignimbus** [comment] 2019-05-15 02:51
It's possible the `resize` event isn't behaving as expected on iOS Safari.  See [this article](https://hackernoon.com/onresize-event-broken-in-mobile-safari-d8469027bf4d), which details what appears to be a race condition.  We may need to ship a workaround using a debounce/timeout function so that the height of the Div100vh component is recalculated more reliably.

**Comment by bignimbus** [comment] 2019-05-24 19:16
@andreivictor so this is interesting - upon further investigation, I believe the novel `rvh` unit that @mvasin came up with is working as expected here.  The issue is that the browser toolbars are being rendered on top of the UI.  So if you're scrolled all the way down, everything looks fine.  But there still exists negative space "behind" the browser toolbars, so Safari will allow the user to scroll.  Ironically, the scroll action helps to get rid of the browser toolbar.

I do not believe there is a reliable software solution to this issue.  Browser vendors can change the appearance of their toolbars at will, and we will have no way of knowing where these toolbars are rendered.  For example, the toolbar could take up 20px of space at the bottom of the viewport and 30px of space at the top on one platform, but the distribution could be completely different on another.

I don't see a way out of this one.

**Comment by mvasin** [comment] 2021-11-07 21:56
Hi @andreivictor! I wasn't able to reproduce the scrollbar issue on https://react-div-100vh-git-switch-from-clientheight-to-in-07120a-vasin.vercel.app (that's the latest beta `react-div-100vh@0.7.0-beta.1`).

I'll close the issue, but happy to re-open if needed.

**Closed by mvasin** 2021-11-07 21:56 UTC
